name: FreshlySqueezed
favicon: null
layout_spectrum: 0.87535
typography_spectrum: 0.88571
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5255779880098999
  lightness: 0.06560543132945895
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
